name: mongodb
services:
  mongodb:
    image: mongodb/mongodb-community-server:8.2-ubuntu2204-slim
    hostname: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - type: bind
        source: ./config/init.js
        target: /docker-entrypoint-initdb.d/init.js
        read_only: true
      - type: volume
        source: mongo-data
        target: /data/db  
    
volumes:
  mongo-data:
networks:
  backend: 