services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:8.2-ubuntu2204-slim
    hostname: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - mongo-data:/data/db  
    
volumes:
  mongo-data:
networks:
  backend: 