name: postgres
services:
  postgres:
    image: postgres:18.4
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql

networks:
  backend:
volumes:
  pg-data: